# Generated by Django 5.0.3 on 2024-03-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("picture", models.FileField(upload_to="media")),
            ],
        ),
    ]
